### ISSUE TITLE
install "DateRangePicker" problem

### ISSUE THREAD

**Issue by thierryH91200** [Timing-GmbH/DateRangePicker#10]
I am the same person who answered you on Charts
I can not use / install "DateRangePicker", could you help me in your turn
I take this opportunity to also make a French localization

**Comment by MrMage** [comment]
Sure! How do you try to install it and what is the problem?

**Comment by thierryH91200** [comment]
here is my install
<img width="2560" alt="capture d ecran 2016-12-21 a 15 28 49" src="https://cloud.githubusercontent.com/assets/6251463/21392910/5a96359c-c792-11e6-90a1-fbca807e28d4.png">

And when I run the application

 no DateRangePicker

where is my error

<img width="2560" alt="capture d ecran 2016-12-21 a 15 32 32" src="https://cloud.githubusercontent.com/assets/6251463/21393164/88242ff4-c793-11e6-940c-985fb3c9c975.png">

**Comment by MrMage** [comment]
No idea. Maybe a problem with Auto Layout? Did you check the picker's frame, e.g. with 

    print(dateRangePicker)
    print(dateRangePicker.frame)
    print(dateRangePicker.isHidden)

Did you compare your approach with the one in DateRangePickerDemo? Also, try removing the `segmentStyle=3` user defined attribute. Or just drag in a "Custom View" manually, then manually change its class to `DateRangePickerView`.

**Comment by thierryH91200** [comment]
i don't understand 
i have  drag in a "Custom View" manually and change the class

**I will start again with a minimalist application**

<img width="2560" alt="capture d ecran 2016-12-21 a 15 28 49" src="https://cloud.githubusercontent.com/assets/6251463/21395568/3a14bb9e-c79d-11e6-85c4-34095e3ab83b.png">
<img width="2560" alt="capture d ecran 2016-12-21 a 16 42 11" src="https://cloud.githubusercontent.com/assets/6251463/21395571/3d23a4bc-c79d-11e6-91a2-cb41ba905456.png">
<img width="2560" alt="capture d ecran 2016-12-21 a 16 47 37" src="https://cloud.githubusercontent.com/assets/6251463/21395574/3f773418-c79d-11e6-9400-cff1537977d9.png">

**Comment by MrMage** [comment]
Did you try removing the view's segmentStyle property in Interface Builder, under "User Defined Runtime Attributes"? That property comes from copying the control from the demo storyboard I think.

**Comment by MrMage** [comment]
Also, does the DateRangePickerDemo work for you?

**Comment by thierryH91200** [comment]
yes for the DateRangePickerDemo  it is ok no problem
yes for the segmentStyle  in Interface Builder i have deleted
<img width="657" alt="capture d ecran 2016-12-21 a 17 23 48" src="https://cloud.githubusercontent.com/assets/6251463/21396969/4c06e692-c7a2-11e6-824f-e747014b7f98.png">

**I will start again with a minimalist project**

**Comment by MrMage** [comment]
Okay, good luck! Let me know what you find.

**Comment by MrMage** [comment]
One more idea: Check the sizes of the subviews of the date range picker:

    rangePicker.subviews.forEach { print($0, $0.frame) }

**Comment by MrMage** [comment]
Or try calling `rangePicker.resizeSubviews(withOldSize: rangePicker.bounds.size)`. If these two don't help, I guess trying with a minimalist project makes the most sense indeed.

**Comment by thierryH91200** [comment]
rangePicker.subviews.forEach { print($0, $0.frame) }
the result is 
<NSSegmentedControl: 0x600000181a00> (0.0, 0.0, 0.0, 0.0) **it 's bad**
and with
        rangePicker.resizeSubviews(withOldSize: rangePicker.bounds.size)
it's ok  and thanks
<img width="582" alt="capture d ecran 2016-12-21 a 17 51 28" src="https://cloud.githubusercontent.com/assets/6251463/21398019/2333db4a-c7a6-11e6-893b-e5154ba029c9.png">

**Comment by MrMage** [comment]
Great to hear! Should be fixed upstream with 9df5863b89698d9a3ab58e617aed98f142ab50fb now.
