### ISSUE TITLE
Past X Days returns 1 day too many?

### ISSUE THREAD

**Issue by DivineDominion** [Timing-GmbH/DateRangePicker#14]
This is more a statement of confusion than an issue :) 

It's now `Sat., 2019-11-02 08:37 +0100` here, and contextual ranges for calendar units work great. E.g. "yesterday" is `DateRange.calendarUnit(-1, .day, hourShift: 0)` and the start/end dates are `2019-10-31 23:00:00 +0000` & `2019-11-01 22:59:59 +0000` respectively. (If you add 1 hour for my time zone offset, that is the whole day of `2019-11-01` except for the last second for apparent reasons.)

The contextual ranges like "Past 7 days" though produce `DateRange.pastDays(7, hourShift: 0)` with `startDate=2019-10-25 22:00:00 +0000` and `endDate=2019-11-02 22:59:59 +0000` (note that we had a DST offset resulting in of 2 hrs from GMT in 2019-10-25) which have a day duration of 8. 

I can get behind both interpreting "the past 7 days" to range "from last Saturday to yesterday (Friday)", or "from last Sunday to today (Saturday)", but the 8-day-range confuses me :)

**Comment by MrMage** [comment]
Good question; I just expected that "Past 7 days" should mean "The past week plus today", so that it also includes today's data. So far no Timing users have complained about that :-)

**Comment by DivineDominion** [comment]
I asked around and there are surprisingly many people not confused about this. In an informal poll, folks favored the 7 days + today option, then it was about evenly split between 7 days including today, and 7 days up to but excluding today. So I guess this is good enough either way? I don't see a point changing what's not broken, and if nobody but me would benefit from making this configurable, let's discard this :)
