### ISSUE TITLE
CocoaPods 2.0 Update?

### ISSUE THREAD

**Issue by MattTimmons** [Timing-GmbH/DateRangePicker#3]
Hello sir! I am able to get CocoaPods update to 2.0? I am also trying to pull the pod directly and I get:

`pod 'DateRangePicker', :git => 'https://github.com/MrMage/DateRangePicker.git'`
[!] Unable to load a podspec from `DateRangePicker.podspec`, skipping:

Can you confirm this behavior?
-MT

**Comment by MrMage** [comment]
Could you please try again with v2.0.1?

**Comment by MattTimmons** [comment]
ok, 2.0.1 now works directly.. but not without specifying the .git.

`pod 'DateRangePicker', '~> 2.0.1'`
[!] Unable to satisfy the following requirements:
- `DateRangePicker (~> 2.0.1)` required by `Podfile`

**Comment by MrMage** [comment]
Maybe the CocoaPods repo needs a bit to update, could you try again in a few hours?

**Comment by MattTimmons** [comment]
Not sure why.. but when you go to https://github.com/CocoaPods/Specs/tree/master/Specs/DateRangePicker

It errors "Failed to load latest commit information."

**Comment by MrMage** [comment]
I think this error was CocoaPods-related.
