### ISSUE TITLE
Implementation Problems

### ISSUE THREAD

**Issue by MattTimmons** [Timing-GmbH/DateRangePicker#4]
Hello,
I have consulted your demo project and can not figure out how to actually implement this..

You say "Just drag the date range picker onto your Storyboard or Nib" So I stuck a custom view in and added the class like I would any other thing.. and nothing. Could you please explain a little more?

Thank you!
-Matt

**Comment by MattTimmons** [comment]
So, I had to "add missing constraints" and the I am finally able to see the segment. But, not the popover creates and exception. This is definitely a little interesting to implement. I love your idea here though!

**Comment by MattTimmons** [comment]
Ok, it may be worth mentioning that you have to add "ExpandedDateRangePickerController.xib" to you project.. the pods did not do that sadly. At least not for me. Sorry for the noise though!

**Comment by MrMage** [comment]
If you add the whole project, you should be able to just add the entire framework (which should contain the xib). If you want, feel free to update the documentation and file a pull request, though.

**Comment by MattTimmons** [comment]
That is was I did (added the xib manually).. not sure how to make that work for Pods, but all good. Thank you sir!
-mt

**Comment by MattTimmons** [comment]
I have found the semitransient popover behavior to be a a pretty cumbersome to me. I suggest transient. Or give us a way to define it. Right now the popovercontroller is private and the popover is just an ivar . Thoughts?

**Comment by MrMage** [comment]
Feel free to expose one of the corresponding properties and file a pull request.
